import type { LegalDoc } from './types';
import { entity } from './entity';

/**
 * Written India-primary — the Digital Personal Data Protection Act, 2023, the
 * Information Technology Act, 2000 with the SPDI Rules, 2011, and the IT
 * (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 — with
 * GDPR/UK GDPR and CCPA/CPRA sections, because the app is distributed on
 * app stores that reach the EU, the UK and California.
 *
 * Rule for editing this file: it must describe what the product actually does.
 * Where a statement depends on the shipped implementation, it carries a
 * placeholder rather than a guess. Removing a placeholder by inventing an
 * answer turns a privacy policy into a misrepresentation.
 */
export const privacyPolicy: LegalDoc = {
  slug: 'privacy-policy',
  title: 'Privacy Policy',
  shortTitle: 'Privacy Policy',
  description:
    'How Aura collects, uses, shares, stores and deletes your personal data, and the rights you have over it under Indian, European and Californian law.',
  summary: [
    'A diary is the most personal thing most people will ever write. This policy says exactly what happens to it.',
    'We process your entries to give the diary back to you — to write it, search it, and print it if you ask. We do not sell your personal data, and we do not advertise against it.',
    'You can export everything, correct anything, and delete your account and its contents at any time.',
    'The summary is here to be read. The numbered sections below are the ones that govern.',
  ],
  sections: [
    {
      id: 'who-we-are',
      heading: '1. Who we are',
      blocks: [
        {
          kind: 'p',
          text: `${entity.tradingName} is operated by ${entity.legalName}, ${entity.entityDescription}, registered as ${entity.registrationNumber}, with its registered office at ${entity.registeredAddress}.`,
        },
        {
          kind: 'p',
          text: `In this policy, "we", "us" and "our" mean ${entity.legalName}. "You" means the person using the ${entity.tradingName} app or this website. We are the Data Fiduciary under the Digital Personal Data Protection Act, 2023 ("DPDP Act") and, where the GDPR applies, the data controller for the personal data described here.`,
        },
        {
          kind: 'p',
          text: `This policy covers the ${entity.tradingName} mobile app, this website, the printed book service, and our support channels. It does not cover any third-party service you reach from them, each of which has its own policy.`,
        },
      ],
    },
    {
      id: 'data-we-collect',
      heading: '2. The personal data we collect',
      blocks: [
        { kind: 'p', text: 'We collect only what the product needs in order to work, in these categories:' },
        {
          kind: 'table',
          head: ['Category', 'What it includes', 'Where it comes from'],
          rows: [
            ['Account data', 'Your name or display name, email address, and authentication identifiers for the sign-in method you choose.', 'You, when you create an account.'],
            ['Diary content', 'Everything you put in your diary: voice recordings you make in the app, the transcripts of those recordings, the entries written from them, your own edits, and any photographs or files you attach.', 'You, as you use the app.'],
            ['Derived memory data', 'The structure Aura builds over your entries so you can search them — for example the people, places, dates and themes it recognises, and the summaries it writes.', 'Generated by us from your diary content.'],
            ['Subscription data', 'Which plan you are on, its status and renewal date, and the identifier your app store returns for the purchase.', 'Apple or Google, when you subscribe. See section 6.'],
            ['Book order data', 'The contents you choose to include, the delivery name, postal address and phone number, order status and tracking references.', 'You, when you order a printed book.'],
            ['Payment data', 'A record that a payment succeeded, its amount, and the last four digits and brand of the instrument where our payment processor returns them.', 'Our payment processor. We do not receive or store full card or bank details.'],
            ['Device and diagnostic data', 'Device model, operating system version, app version, language, crash reports and error logs.', 'Collected automatically by the app.'],
            ['Support data', 'The messages you send us and what we send back.', 'You, when you contact support.'],
          ],
        },
        {
          kind: 'note',
          text: 'We do not require your precise location, your contacts, or access to your camera roll for the app to work. Where a feature needs one of these, the app asks first and you can say no and keep using everything else.',
        },
      ],
    },
    {
      id: 'sensitive-data',
      heading: '3. Diary entries and sensitive personal data',
      blocks: [
        {
          kind: 'p',
          text: 'A diary is not an ordinary category of data. What you tell Aura about your day may reveal your health, your mental health, your religious or political beliefs, your sex life or sexual orientation, your relationships, or your finances — not because we ask for any of it, but because that is what a life contains.',
        },
        {
          kind: 'p',
          text: 'We treat all diary content as sensitive by default, whether or not a particular entry legally qualifies as such. Under the SPDI Rules, 2011 this is sensitive personal data or information. Under the GDPR, entries that reveal one of the categories in Article 9 are special category data, and we process them on the basis of your explicit consent, given when you create your account and able to be withdrawn at any time.',
        },
        {
          kind: 'p',
          text: 'We do not use your diary content to profile you for advertising, we do not build audience segments from it, and we do not disclose it to anyone except as set out in section 7.',
        },
      ],
    },
    {
      id: 'why-we-process',
      heading: '4. Why we process it, and on what legal basis',
      blocks: [
        {
          kind: 'p',
          text: 'Under the DPDP Act we process your personal data with your consent, or for the legitimate uses that Act permits. Under the GDPR the corresponding legal bases are set out below.',
        },
        {
          kind: 'table',
          head: ['Purpose', 'Data used', 'DPDP Act basis', 'GDPR basis'],
          rows: [
            ['To create and run your account', 'Account data', 'Consent', 'Performance of a contract (Art. 6(1)(b))'],
            ['To transcribe what you say and write your diary entry from it', 'Diary content', 'Consent', 'Performance of a contract; explicit consent for special category data (Art. 9(2)(a))'],
            ['To let you search and rediscover your own memories', 'Diary content, derived memory data', 'Consent', 'Performance of a contract'],
            ['To sync your diary across your devices', 'Account data, diary content', 'Consent', 'Performance of a contract'],
            ['To take payment and manage your subscription', 'Subscription data, payment data', 'Consent; performance of a contract', 'Performance of a contract'],
            ['To print, bind and deliver a book you order', 'Book order data, the entries you chose', 'Consent; performance of a contract', 'Performance of a contract'],
            ['To answer your support requests', 'Support data, account data', 'Legitimate use', 'Legitimate interests (Art. 6(1)(f)) — answering you'],
            ['To keep the service working, diagnose crashes and fix bugs', 'Device and diagnostic data', 'Legitimate use', 'Legitimate interests — a service that functions'],
            ['To prevent fraud, abuse and unauthorised access', 'Account data, device data', 'Legitimate use', 'Legitimate interests — securing the service'],
            ['To meet a legal, tax or regulatory obligation', 'Whatever the obligation requires', 'Legitimate use — compliance with law', 'Legal obligation (Art. 6(1)(c))'],
          ],
        },
        {
          kind: 'p',
          text: 'We will not use your personal data for a new purpose that is incompatible with the ones above without telling you first and, where the law requires it, asking for your consent.',
        },
      ],
    },
    {
      id: 'ai-processing',
      heading: '5. How AI processing works',
      blocks: [
        {
          kind: 'p',
          text: 'Aura uses automated speech recognition and language models to turn what you say into a written entry, to summarise it, and to recognise the people, places and themes that make your diary searchable.',
        },
        { kind: 'p', text: 'What this means in practice:' },
        {
          kind: 'ul',
          items: [
            `Your recordings and entries are sent to the AI providers listed in section 7 so they can be transcribed and written up. ${'[[AI_PROVIDERS_AND_REGIONS]]'}`,
            `Whether your content is used to train or improve AI models: ${'[[AI_TRAINING_STANCE]]'}. If we ever propose to use your diary content to train a model, we will ask for your consent first and it will be a genuine choice, not a condition of using the app.`,
            `How long an AI provider retains what we send it: ${'[[AI_PROVIDER_RETENTION]]'}.`,
            'AI output can be wrong. An entry Aura writes is a draft of your day, not a record of fact, and you can edit or delete any part of it.',
            'You can turn AI features off in the app and keep writing your diary yourself. Turning them off stops new content being sent for AI processing.',
          ],
        },
        {
          kind: 'p',
          text: 'We do not use automated decision-making that produces legal effects concerning you or similarly significantly affects you, within the meaning of Article 22 of the GDPR.',
        },
      ],
    },
    {
      id: 'payments',
      heading: '6. Payments and subscriptions',
      blocks: [
        {
          kind: 'p',
          text: 'Subscriptions bought inside the app are processed by Apple or Google under their own terms and privacy policies. They take the payment; we receive confirmation that it succeeded, the plan and its status, and an identifier for the purchase. We never receive your card number.',
        },
        {
          kind: 'p',
          text: `Payments for printed books are processed by ${'[[PAYMENT_PROCESSOR]]'}. Card and bank details are collected and held by that processor, not by us. We keep the record of the transaction we need for accounting, tax and warranty purposes.`,
        },
      ],
    },
    {
      id: 'sharing',
      heading: '7. Who we share personal data with',
      blocks: [
        {
          kind: 'p',
          text: 'We do not sell your personal data. We do not share it for cross-context behavioural advertising. We do not give anyone access to your diary in exchange for money or anything else of value.',
        },
        {
          kind: 'p',
          text: 'We share personal data only with the service providers we need in order to run the product. Each of them is bound by contract to process it only on our instructions, to keep it confidential, and to protect it.',
        },
        {
          kind: 'table',
          head: ['Recipient', 'What they receive', 'Why', 'Where they process it'],
          rows: [
            ['[[CLOUD_HOSTING_PROVIDER]]', 'Account data, diary content, derived memory data', 'Hosting and storage', '[[HOSTING_REGION]]'],
            ['[[AI_PROVIDER]]', 'Voice recordings, transcripts and entry text', 'Transcription and diary writing', '[[AI_REGION]]'],
            ['[[PAYMENT_PROCESSOR]]', 'Payment and order data', 'Taking payment for books', '[[PAYMENT_REGION]]'],
            ['[[PRINT_PARTNER]]', 'The entries you chose to print, delivery name and address', 'Printing, binding and dispatch', '[[PRINT_REGION]]'],
            ['[[LOGISTICS_PARTNER]]', 'Delivery name, address and phone number', 'Delivering your parcel', '[[LOGISTICS_REGION]]'],
            ['[[SUPPORT_TOOLING]]', 'Support data and account data', 'Running our support inbox', '[[SUPPORT_REGION]]'],
            ['[[ANALYTICS_OR_CRASH_TOOLING]]', 'Device and diagnostic data', 'Crash reporting and reliability', '[[ANALYTICS_REGION]]'],
          ],
        },
        { kind: 'p', text: 'We will also disclose personal data where we are legally required to:' },
        {
          kind: 'ul',
          items: [
            'to comply with a valid order of a court or of a lawful authority, or a requirement under Indian law, including the Information Technology Act, 2000;',
            'to establish, exercise or defend a legal claim;',
            'to protect the rights, safety or property of a person where there is a genuine and immediate risk.',
          ],
        },
        {
          kind: 'p',
          text: 'Where the law allows us to tell you that your data has been demanded, we will. If we are ever part of a merger, acquisition or sale of assets, your personal data may transfer with the business, and this policy will continue to apply to it until you are given notice of a replacement.',
        },
      ],
    },
    {
      id: 'transfers',
      heading: '8. International transfers',
      blocks: [
        {
          kind: 'p',
          text: `Your personal data is stored in ${'[[PRIMARY_STORAGE_REGION]]'}. Some of the providers in section 7 process it in other countries.`,
        },
        {
          kind: 'p',
          text: 'Transfers out of India are made in accordance with section 16 of the DPDP Act and any restriction the Central Government notifies. For personal data protected by the GDPR or UK GDPR, transfers outside the EEA or the UK are made under the European Commission’s Standard Contractual Clauses, the UK International Data Transfer Addendum, or an adequacy decision, together with any additional safeguards the transfer requires.',
        },
        {
          kind: 'p',
          text: `You can ask us for a copy of the safeguards that apply to a particular transfer by writing to ${entity.privacyEmail}.`,
        },
      ],
    },
    {
      id: 'retention',
      heading: '9. How long we keep it',
      blocks: [
        {
          kind: 'p',
          text: 'We keep your diary for as long as your account exists, because that is the point of it. Everything else is kept only as long as it is needed.',
        },
        {
          kind: 'table',
          head: ['What', 'How long'],
          rows: [
            ['Diary content and derived memory data', 'Until you delete it, or until your account is deleted'],
            ['A deleted entry', `Removed from your account immediately and purged from backups within ${'[[BACKUP_PURGE_WINDOW]]'}`],
            ['Your account after you delete it', `Deleted within ${'[[ACCOUNT_DELETION_WINDOW]]'}, apart from anything we must keep by law`],
            ['An inactive account', `${'[[INACTIVITY_POLICY]]'}`],
            ['Book order and delivery records', `${'[[ORDER_RECORD_RETENTION]]'}, to handle warranty, returns and disputes`],
            ['Invoices, tax and accounting records', 'For the period required by Indian tax law, currently eight years'],
            ['Device and diagnostic data', `${'[[DIAGNOSTIC_RETENTION]]'}`],
            ['Support conversations', `${'[[SUPPORT_RETENTION]]'}`],
          ],
        },
        {
          kind: 'p',
          text: 'When a retention period ends we delete the personal data or irreversibly anonymise it, so that it can no longer be linked back to you.',
        },
      ],
    },
    {
      id: 'security',
      heading: '10. Security',
      blocks: [
        {
          kind: 'p',
          text: `We take reasonable security safeguards to protect personal data against loss, unauthorised access, disclosure, alteration and destruction, as required by section 8(5) of the DPDP Act and Rule 8 of the SPDI Rules. The measures we operate are: ${'[[SECURITY_MEASURES]]'}.`,
        },
        {
          kind: 'p',
          text: 'You can also protect your diary at your end by keeping the app behind your device passcode, Face ID or fingerprint, and by using a strong, unique sign-in.',
        },
        {
          kind: 'p',
          text: `No service can promise that a breach will never happen. If a personal data breach occurs we will notify the Data Protection Board of India and every affected user in the form and within the time the DPDP Act and its rules require, and — where the GDPR applies — the competent supervisory authority within 72 hours under Article 33, and affected individuals under Article 34 where the risk is high.`,
        },
      ],
    },
    {
      id: 'your-rights',
      heading: '11. Your rights',
      blocks: [
        {
          kind: 'p',
          text: 'Whoever and wherever you are, you can do all of the following from inside the app or by writing to us: get a copy of your data, correct it, export it, and delete it.',
        },
        { kind: 'p', text: 'If you are in India, the DPDP Act gives you the right:' },
        {
          kind: 'ul',
          items: [
            'to obtain a summary of the personal data we process about you and the processing activities we undertake;',
            'to know the identities of the other Data Fiduciaries and Data Processors with whom we have shared it, and what was shared;',
            'to correction, completion, updating and erasure of your personal data;',
            'to nominate another person to exercise these rights on your behalf if you die or become incapacitated;',
            'to a readily available means of grievance redressal — see section 14;',
            'to withdraw a consent you gave, as easily as you gave it.',
          ],
        },
        {
          kind: 'p',
          text: 'If the GDPR or UK GDPR applies to you, you also have the rights of access, rectification, erasure, restriction of processing, data portability, and objection to processing based on legitimate interests, together with the right to withdraw consent at any time without affecting processing already carried out.',
        },
        {
          kind: 'p',
          text: 'If you are a California resident, the CCPA as amended by the CPRA gives you the right to know what we collect and why, the right to delete, the right to correct, the right to opt out of sale or sharing, and the right to limit the use of sensitive personal information. We do not sell or share personal information as those terms are defined, and we use sensitive personal information only to provide the service you asked for. We will not discriminate against you for exercising any of these rights. An authorised agent may act for you on proof of authorisation.',
        },
        {
          kind: 'p',
          text: `To exercise any right, use the controls in the app or write to ${entity.privacyEmail}. We will verify your identity before acting, and respond within the time the applicable law allows — and in any case within 30 days.`,
        },
      ],
    },
    {
      id: 'children',
      heading: '12. Children',
      blocks: [
        {
          kind: 'p',
          text: `${entity.tradingName} is not intended for children. Under the DPDP Act, a child in India is a person under 18, and we may process a child’s personal data only with verifiable consent from a parent or lawful guardian. We do not knowingly collect personal data from a child without it, and we do not undertake tracking, behavioural monitoring or targeted advertising directed at children.`,
        },
        {
          kind: 'p',
          text: `If you believe a child has given us personal data without that consent, write to ${entity.privacyEmail} and we will delete it.`,
        },
      ],
    },
    {
      id: 'cookies',
      heading: '13. Cookies and similar technologies',
      blocks: [
        {
          kind: 'p',
          text: 'This website does not set advertising or analytics cookies. The app uses local storage on your device to keep you signed in and to hold your settings. The detail is in our Cookie Policy.',
        },
      ],
    },
    {
      id: 'grievance',
      heading: '14. Grievance redressal',
      blocks: [
        {
          kind: 'p',
          text: `If you are unhappy with how we have handled your personal data, tell us first. Our Grievance Officer, appointed under Rule 3(2) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and acting as our contact under the DPDP Act, is:`,
        },
        {
          kind: 'note',
          text: `${entity.grievanceOfficerName}, Grievance Officer\n${entity.legalName}\n${entity.grievanceOfficerAddress}\nEmail: ${entity.grievanceOfficerEmail}\nPhone: ${entity.grievanceOfficerPhone}`,
        },
        {
          kind: 'p',
          text: 'We acknowledge every complaint within 24 hours and resolve it within 15 days of receipt, as those Rules require.',
        },
        {
          kind: 'p',
          text: 'If we have not resolved it, you may complain to the Data Protection Board of India in the manner prescribed under the DPDP Act. If the GDPR applies to you, you may complain to your local supervisory authority or, in the UK, to the Information Commissioner’s Office. None of this affects your right to a remedy in court.',
        },
        { kind: 'p', text: `Our representative in the EU and UK for the purposes of Article 27 of the GDPR is ${entity.euRepresentative}.` },
      ],
    },
    {
      id: 'changes',
      heading: '15. Changes to this policy',
      blocks: [
        {
          kind: 'p',
          text: 'We update this policy when the product changes or the law does. If a change materially affects your rights or how we use your diary, we will tell you in the app or by email before it takes effect, and where the law requires consent we will ask for it rather than assume it.',
        },
        { kind: 'p', text: `This version takes effect on ${entity.effectiveDate} and was last updated on ${entity.lastUpdated}. Earlier versions are available on request.` },
      ],
    },
    {
      id: 'contact',
      heading: '16. How to contact us',
      blocks: [
        {
          kind: 'note',
          text: `${entity.legalName}\n${entity.registeredAddress}\nPrivacy: ${entity.privacyEmail}\nSupport: ${entity.supportEmail}\nData protection contact: ${entity.dataProtectionContact}`,
        },
      ],
    },
  ],
};
